package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestExtractAndSaveFiles(t *testing.T) {
	sample := "Here is your requested project structure:\n```json\n{\n  \"files\": [\n    {\n      \"filename\": \"test_out/app.js\",\n      \"code\": \"console.log('generated by claude');\"\n    }\n  ]\n}\n```\nEnjoy!"

	extractAndSaveFiles(sample)

	target := filepath.Join("Sandbox", "test_out", "app.js")
	data, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("Failed to read created file %s: %v", target, err)
	}

	expected := "console.log('generated by claude');"
	if string(data) != expected {
		t.Fatalf("Expected content %q, got %q", expected, string(data))
	}

	// Clean up
	_ = os.RemoveAll(filepath.Join("Sandbox", "test_out"))
}

func TestExtractActions(t *testing.T) {
	// Test case 1: root-level action: "run" with batch file in files
	payload1 := &ExtractedPayload{
		Action: "run",
		Files: []ExtractedFile{
			{Filename: "script.bat", Code: "@echo off\necho hello"},
		},
	}
	actions1 := extractActions(payload1, []string{"script.bat"})
	if len(actions1) != 1 {
		t.Fatalf("Expected 1 action, got %d", len(actions1))
	}
	if actions1[0].Target != "script.bat" || actions1[0].Type != "run" {
		t.Fatalf("Expected action target 'script.bat' and type 'run', got %+v", actions1[0])
	}

	// Test case 2: file-level action: "run"
	payload2 := &ExtractedPayload{
		Files: []ExtractedFile{
			{Filename: "setup.bat", Code: "@echo off", Action: "run"},
			{Filename: "readme.txt", Code: "hello"},
		},
	}
	actions2 := extractActions(payload2, []string{"setup.bat", "readme.txt"})
	if len(actions2) != 1 {
		t.Fatalf("Expected 1 action, got %d", len(actions2))
	}
	if actions2[0].Target != "setup.bat" {
		t.Fatalf("Expected action target 'setup.bat', got %s", actions2[0].Target)
	}

	// Test case 3: actions array
	payload3 := &ExtractedPayload{
		Actions: []any{
			map[string]any{"type": "run", "target": "task1.bat"},
			"run task2.bat",
		},
	}
	actions3 := extractActions(payload3, nil)
	if len(actions3) != 2 {
		t.Fatalf("Expected 2 actions, got %d", len(actions3))
	}
	if actions3[0].Target != "task1.bat" || actions3[1].Target != "task2.bat" {
		t.Fatalf("Expected task1.bat and task2.bat, got %+v", actions3)
	}
}

func TestExecuteActionSilently_BatchScript(t *testing.T) {
	_ = os.MkdirAll("Sandbox", 0755)

	var scriptName string
	var scriptContent string

	if runtime.GOOS == "windows" {
		scriptName = "test_run.bat"
		scriptContent = "@echo off\necho Step 1: Starting batch process...\necho Step 2: Running silent operations...\necho Step 3: Done!\n"
	} else {
		scriptName = "test_run.sh"
		scriptContent = "#!/bin/sh\necho 'Step 1: Starting batch process...'\necho 'Step 2: Running silent operations...'\necho 'Step 3: Done!'\n"
	}

	scriptPath := filepath.Join("Sandbox", scriptName)
	if err := os.WriteFile(scriptPath, []byte(scriptContent), 0755); err != nil {
		t.Fatalf("Failed to create test script: %v", err)
	}
	defer os.Remove(scriptPath)

	action := ActionItem{
		Type:       "run",
		Target:     scriptName,
		WorkingDir: "Sandbox",
	}

	result := executeActionSilently(action)
	if !result.Success {
		t.Fatalf("Execution failed: %v (ExitCode: %d, Output: %s)", result.Error, result.ExitCode, result.Output)
	}

	if !strings.Contains(result.Output, "Step 1: Starting batch process...") {
		t.Fatalf("Expected output to contain 'Step 1: Starting batch process...', got:\n%s", result.Output)
	}
	if !strings.Contains(result.Output, "Step 3: Done!") {
		t.Fatalf("Expected output to contain 'Step 3: Done!', got:\n%s", result.Output)
	}

	// Verify execution.log was written
	logPath := filepath.Join("Sandbox", "execution.log")
	logData, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatalf("Failed to read execution.log: %v", err)
	}
	if !strings.Contains(string(logData), "EXECUTION STARTED") {
		t.Fatalf("Expected execution.log to contain 'EXECUTION STARTED', got:\n%s", string(logData))
	}
	if !strings.Contains(string(logData), "Step 2: Running silent operations...") {
		t.Fatalf("Expected execution.log to contain logged lines, got:\n%s", string(logData))
	}
}

func TestExtractAndSaveFiles_WithActionRun(t *testing.T) {
	_ = os.MkdirAll("Sandbox", 0755)

	var scriptExt string
	var scriptBody string
	if runtime.GOOS == "windows" {
		scriptExt = ".bat"
		scriptBody = "@echo off\necho End-to-End Action Execution Test Success"
	} else {
		scriptExt = ".sh"
		scriptBody = "#!/bin/sh\necho 'End-to-End Action Execution Test Success'"
	}

	sample := "```json\n{\n  \"action\": \"run\",\n  \"files\": [\n    {\n      \"filename\": \"e2e_runner" + scriptExt + "\",\n      \"code\": \"" + strings.ReplaceAll(scriptBody, "\n", "\\n") + "\"\n    }\n  ]\n}\n```"

	extractAndSaveFiles(sample)

	target := filepath.Join("Sandbox", "e2e_runner"+scriptExt)
	if _, err := os.Stat(target); err != nil {
		t.Fatalf("Expected file to be saved at %s", target)
	}
	defer os.Remove(target)

	// Check execution log
	logPath := filepath.Join("Sandbox", "execution.log")
	logData, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatalf("Failed to read execution.log: %v", err)
	}
	if !strings.Contains(string(logData), "End-to-End Action Execution Test Success") {
		t.Fatalf("Expected log to contain execution output, got:\n%s", string(logData))
	}
}

func TestNestedDirectoryActionExecution(t *testing.T) {
	_ = os.MkdirAll(filepath.Join("Sandbox", "tts"), 0755)

	var scriptExt string
	var scriptBody string
	if runtime.GOOS == "windows" {
		scriptExt = ".bat"
		scriptBody = "@echo off\necho Nested Directory Execution Success"
	} else {
		scriptExt = ".sh"
		scriptBody = "#!/bin/sh\necho 'Nested Directory Execution Success'"
	}

	sample := "```json\n{\n  \"action\": \"run\",\n  \"files\": [\n    {\n      \"filename\": \"tts/nested_runner" + scriptExt + "\",\n      \"code\": \"" + strings.ReplaceAll(scriptBody, "\n", "\\n") + "\"\n    }\n  ]\n}\n```"

	extractAndSaveFiles(sample)

	target := filepath.Join("Sandbox", "tts", "nested_runner"+scriptExt)
	if _, err := os.Stat(target); err != nil {
		t.Fatalf("Expected file at %s", target)
	}
	defer os.RemoveAll(filepath.Join("Sandbox", "tts"))

	logPath := filepath.Join("Sandbox", "execution.log")
	logData, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatalf("Failed to read execution.log: %v", err)
	}
	if !strings.Contains(string(logData), "Nested Directory Execution Success") {
		t.Fatalf("Expected log to contain nested execution output, got:\n%s", string(logData))
	}
}

func TestExtractClaudeAttachCommands(t *testing.T) {
	text := "Please attach the file: `attach src/main.rs` and attach a file or attach config.json. Also I will attach this to the report."
	files := extractClaudeAttachCommands(text)
	if len(files) != 2 {
		t.Fatalf("Expected 2 requested files (src/main.rs, config.json), got %d: %v", len(files), files)
	}
	if files[0] != "src/main.rs" || files[1] != "config.json" {
		t.Fatalf("Unexpected requested files: %v", files)
	}
}

func TestGetMimeType(t *testing.T) {
	cases := map[string]string{
		"test.py":   "text/plain",
		"index.html": "text/html",
		"style.css":  "text/css",
		"app.js":     "application/javascript",
		"data.json":  "application/json",
		"image.png":  "image/png",
		"doc.pdf":    "application/pdf",
		"unknown.xyz": "application/octet-stream",
	}

	for filename, expected := range cases {
		actual := getMimeType(filename)
		if actual != expected {
			t.Errorf("For %s, expected %s, got %s", filename, expected, actual)
		}
	}
}

func TestCreateFilePayload(t *testing.T) {
	_ = os.MkdirAll("Sandbox", 0755)
	testPath := filepath.Join("Sandbox", "sample_test_payload.txt")
	testContent := "hello claude attachment"
	if err := os.WriteFile(testPath, []byte(testContent), 0644); err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}
	defer os.Remove(testPath)

	fp, err := createFilePayload("sample_test_payload.txt", testPath)
	if err != nil {
		t.Fatalf("createFilePayload returned error: %v", err)
	}

	if fp.Name != "sample_test_payload.txt" {
		t.Errorf("Expected Name 'sample_test_payload.txt', got %s", fp.Name)
	}
	if fp.Encoding != "base64" {
		t.Errorf("Expected Encoding 'base64', got %s", fp.Encoding)
	}
	if fp.Type != "text/plain" {
		t.Errorf("Expected Type 'text/plain', got %s", fp.Type)
	}
	if fp.Content == "" {
		t.Errorf("Expected non-empty base64 Content")
	}
}

func TestResolveSandboxAttach(t *testing.T) {
	_ = os.MkdirAll("Sandbox", 0755)
	testPath := filepath.Join("Sandbox", "attach_test.txt")
	_ = os.WriteFile(testPath, []byte("attachment contents"), 0644)
	defer os.Remove(testPath)

	res := resolveSandboxAttach("attach attach_test.txt please review this")
	if res == nil {
		t.Fatalf("Expected non-nil AttachResult")
	}
	if len(res.Files) != 1 {
		t.Fatalf("Expected 1 attached file, got %d", len(res.Files))
	}
	if res.Files[0].Name != "attach_test.txt" {
		t.Errorf("Expected file name 'attach_test.txt', got %s", res.Files[0].Name)
	}
	if res.Prompt != "please review this" {
		t.Errorf("Expected prompt 'please review this', got %q", res.Prompt)
	}
}

func TestModelManagement_GrokClaudeGemini(t *testing.T) {
	// Test setActiveModel
	setActiveModel("grok")
	if m := getActiveModel(); m != "grok" {
		t.Errorf("Expected active model 'grok', got %s", m)
	}

	setActiveModel("x")
	if m := getActiveModel(); m != "grok" {
		t.Errorf("Expected active model 'grok' for alias 'x', got %s", m)
	}

	setActiveModel("gemini")
	if m := getActiveModel(); m != "gemini" {
		t.Errorf("Expected active model 'gemini', got %s", m)
	}

	setActiveModel("claude")
	if m := getActiveModel(); m != "claude" {
		t.Errorf("Expected active model 'claude', got %s", m)
	}

	// Test 3-way toggle cycle
	setActiveModel("claude")
	if next := toggleActiveModel(); next != "gemini" {
		t.Errorf("Expected next model after claude to be 'gemini', got %s", next)
	}
	if next := toggleActiveModel(); next != "grok" {
		t.Errorf("Expected next model after gemini to be 'grok', got %s", next)
	}
	if next := toggleActiveModel(); next != "claude" {
		t.Errorf("Expected next model after grok to be 'claude', got %s", next)
	}

	// Test Display Names
	if name := getProviderDisplayName("grok"); name != "Grok" {
		t.Errorf("Expected display name 'Grok', got %s", name)
	}
	if name := getProviderDisplayName("gemini"); name != "Gemini" {
		t.Errorf("Expected display name 'Gemini', got %s", name)
	}
	if name := getProviderDisplayName("claude"); name != "Claude" {
		t.Errorf("Expected display name 'Claude', got %s", name)
	}

	// Test Colors
	if col := getModelColor("grok"); col != colorGrok {
		t.Errorf("Expected colorGrok for grok, got %s", col)
	}
	if col := getModelColor("gemini"); col != colorGemini {
		t.Errorf("Expected colorGemini for gemini, got %s", col)
	}
	if col := getModelColor("claude"); col != colorClaude {
		t.Errorf("Expected colorClaude for claude, got %s", col)
	}
}
